# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0FpOuLye9VXK5PEiji3cOljW4gDJp4v
"""

import math

# Hàm giải phương trình bậc hai
def giai_phuong_trinh_bac_hai(a, b, c):
    # Kiểm tra trường hợp a = 0 (phương trình trở thành phương trình bậc nhất)
    if a == 0:
        if b != 0:
            x = -c / b
            print(f"Phương trình bậc nhất có nghiệm duy nhất: x = {x}")
        else:
            if c == 0:
                print("Phương trình có vô số nghiệm.")
            else:
                print("Phương trình vô nghiệm.")
    else:
        # Tính delta
        delta = b**2 - 4*a*c
        # Xử lý theo giá trị của delta
        if delta > 0:
            x1 = (-b + math.sqrt(delta)) / (2*a)
            x2 = (-b - math.sqrt(delta)) / (2*a)
            print(f"Phương trình có hai nghiệm phân biệt: x1 = {x1}, x2 = {x2}")
        elif delta == 0:
            x = -b / (2*a)
            print(f"Phương trình có nghiệm kép: x = {x}")
        else:
            print("Phương trình vô nghiệm trong tập số thực.")

# Nhập giá trị a, b, c từ người dùng
a = float(input("Nhập giá trị của a: "))
b = float(input("Nhập giá trị của b: "))
c = float(input("Nhập giá trị của c: "))

# Gọi hàm giải phương trình
giai_phuong_trinh_bac_hai(a, b, c)