# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npdpcnK32M-erVQn7d9qTcrp3kjsfcbQ
"""

n = int(input("Enter a positive integer:"))
print(n)

s = 0
i = 0

while i < n:
    s += i
    i += 2

print(f"The sum of even numbers less than {n} is {s}")

