# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0FpOuLye9VXK5PEiji3cOljW4gDJp4v
"""

n = int(input("Enter a positive integer: "))  # Take user input for the positive integer
s = 0  # Initialize the sum to 0

# Use a for loop to sum the numbers from 0 to n
for i in range(n + 1):
    s += i  # Add each number i to the sum

# Output the result
print(f"The sum of 1 to {n} is {s}")